# Generated by Django 2.1.5 on 2022-03-09 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=300)),
                ('date', models.DateTimeField(auto_now=True)),
                ('quality_rate', models.IntegerField(default=0)),
                ('music_rate', models.IntegerField(default=0)),
                ('community_rate', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('publisher', models.CharField(max_length=128)),
                ('price', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=300)),
                ('category', models.CharField(max_length=128)),
                ('poster', models.ImageField(upload_to='')),
                ('store_link', models.URLField()),
                ('avg_quality_rate', models.FloatField(default=0.0)),
                ('avg_music_rate', models.FloatField(default=0.0)),
                ('avg_community_rate', models.FloatField(default=0.0)),
                ('views', models.IntegerField(default=0)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamehub.Game'),
        ),
    ]
